include $(GNUSTEP_MAKEFILES)/common.make
BUNDLE_NAME = Logging

BUNDLE_EXTENSION =

BUNDLE_INSTALL_DIR = $(GNUSTEP_INSTALLATION_DIR)/Library/ApplicationSupport/TalkSoup/InFilters

Logging_PRINCIPAL_CLASS = Logging

Logging_FRAMEWORKS = -lTalkSoupBundles

Logging_OBJC_FILES = Logging.m

GUI_LIBS = 

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/bundle.make
-include GNUmakefile.postamble

