include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECTS = Highlighting MessageInTab KeepAlive Debold \
              Decolorizer Deunderline Dereverse Logging

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
-include GNUmakefile.postamble
