include $(GNUSTEP_MAKEFILES)/common.make
BUNDLE_NAME = KeepAlive

BUNDLE_EXTENSION =

BUNDLE_INSTALL_DIR = $(GNUSTEP_INSTALLATION_DIR)/Library/ApplicationSupport/TalkSoup/InFilters

KeepAlive_PRINCIPAL_CLASS = KeepAlive

KeepAlive_FRAMEWORKS = -lTalkSoupBundles

KeepAlive_OBJC_FILES = KeepAlive.m

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/bundle.make
-include GNUmakefile.postamble

