include $(GNUSTEP_MAKEFILES)/common.make
BUNDLE_NAME = Skeleton

BUNDLE_EXTENSION =

BUNDLE_INSTALL_DIR = $(GNUSTEP_INSTALLATION_DIR)/Library/ApplicationSupport/TalkSoup/InFilters

Skeleton_PRINCIPAL_CLASS = Skeleton

Skeleton_FRAMEWORKS = -lTalkSoupBundles

Skeleton_OBJC_FILES = Skeleton.m

GUI_LIBS = 

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/bundle.make
-include GNUmakefile.postamble

