include $(GNUSTEP_MAKEFILES)/common.make
BUNDLE_NAME = Colorizer

BUNDLE_EXTENSION =

BUNDLE_INSTALL_DIR = $(GNUSTEP_INSTALLATION_DIR)/Library/ApplicationSupport/TalkSoup/OutFilters

Colorizer_PRINCIPAL_CLASS = Colorizer

Colorizer_FRAMEWORKS = -lTalkSoupBundles

Colorizer_OBJC_FILES = Colorizer.m

GUI_LIBS = 

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/bundle.make
-include GNUmakefile.postamble

