include $(GNUSTEP_MAKEFILES)/common.make
BUNDLE_NAME = Piper

BUNDLE_EXTENSION =

BUNDLE_INSTALL_DIR = $(GNUSTEP_INSTALLATION_DIR)/Library/ApplicationSupport/TalkSoup/OutFilters

Piper_PRINCIPAL_CLASS = Piper

Piper_FRAMEWORKS = -lTalkSoupBundles

Piper_OBJC_FILES = Piper.m

GUI_LIBS = 

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/bundle.make
-include GNUmakefile.postamble

