include $(GNUSTEP_MAKEFILES)/common.make
BUNDLE_NAME = Deunderline

BUNDLE_EXTENSION =

BUNDLE_INSTALL_DIR = $(GNUSTEP_INSTALLATION_DIR)/Library/ApplicationSupport/TalkSoup/InFilters

Deunderline_PRINCIPAL_CLASS = Deunderline

Deunderline_FRAMEWORKS = -lTalkSoupBundles

Deunderline_OBJC_FILES = Deunderline.m

GUI_LIBS = 

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/bundle.make
-include GNUmakefile.postamble

