include $(GNUSTEP_MAKEFILES)/common.make
BUNDLE_NAME = NetclassesInput

BUNDLE_EXTENSION =

BUNDLE_INSTALL_DIR = $(GNUSTEP_INSTALLATION_DIR)/Library/ApplicationSupport/TalkSoup/Input

NetclassesInput_BUNDLE_LIBS = -lnetclasses

NetclassesInput_PRINCIPAL_CLASS = NetclassesInput

main = main.m Functions.m

NetclassesInput_OBJC_FILES = $(main)

GUI_LIBS = 

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/bundle.make
-include GNUmakefile.postamble

