include $(GNUSTEP_MAKEFILES)/common.make

FRAMEWORK_NAME = TalkSoupBundles

TalkSoupBundles_HEADER_FILES = TalkSoup.h TalkSoupProtocols.h TalkSoupMisc.h

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/framework.make
-include GNUmakefile.postamble
	
