before-all::
	$(MKDIRS) $(GNUSTEP_OBJ_DIR)/netclasses
	$(MKDIRS) $(GNUSTEP_OBJ_DIR)/Views
	$(MKDIRS) $(GNUSTEP_OBJ_DIR)/Models
	$(MKDIRS) $(GNUSTEP_OBJ_DIR)/Controllers
	$(MKDIRS) $(GNUSTEP_OBJ_DIR)/Windows
	$(MKDIRS) $(GNUSTEP_OBJ_DIR)/Misc
