include $(GNUSTEP_MAKEFILES)/common.make
BUNDLE_NAME = Decolorizer

BUNDLE_EXTENSION =

BUNDLE_INSTALL_DIR = $(GNUSTEP_INSTALLATION_DIR)/Library/ApplicationSupport/TalkSoup/InFilters

Decolorizer_PRINCIPAL_CLASS = Decolorizer

Decolorizer_FRAMEWORKS = -lTalkSoupBundles

Decolorizer_OBJC_FILES = Decolorizer.m

GUI_LIBS = 

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/bundle.make
-include GNUmakefile.postamble

